### ISSUE TITLE
Permission to modify logo and use in webpack-common-shake

### ISSUE THREAD

**Issue by indutny** [webpack/media#12]
Hello!

I'd like to modify (make it shake) and use logo in my [webpack-common-shake][0] plugin. May I have your permission to do this?

Thanks!

[0]: https://github.com/indutny/webpack-common-shake

**Comment by indutny** [comment]
cc @TheLarkInn

**Comment by TheLarkInn** [comment]
Yes you may!!! If we have to modify what is shown due to changes in license etc. we will likely reach out!!!

**Comment by indutny** [comment]
Thanks!
