### ISSUE TITLE
Permission to modify logo and use in webpack-china

### ISSUE THREAD

**Issue by shaodahong** [webpack/media#13]
Hello!

I want to modify this logo(I need to change the color, similar to the Chinese red) to make it with Chinese characteristics, Used in [webpack-china](https://github.com/webpack-china).  May I have your permission to do this? @TheLarkInn 

Thanks!

**Comment by jhnns** [comment]
Hey @shaodahong 👋 thanks for asking. You can change the colors of the logo. I think, red fits perfectly well with China :) 
However, please don't change other characteristics and especially don't skew it (as it has happened with the current webpack-china logo).

**Comment by RichieRichElDiablo** [comment]
Lol

**Comment by alexander-akait** [comment]
Answered
