### ISSUE TITLE
Logo usage on nodejs.dev

### ISSUE THREAD

**Issue by benhalverson** [webpack/media#15]
The nodejs.dev website dev team is interested in using the webpack logo on the homepage.
https://github.com/nodejs/nodejs.dev/issues/637#issuecomment-642806710

For reference https://nodejs.dev

How do we proceed with this?

**Comment by sokra** [comment]
Technically you can get a "written consent" by the openjs foundation, but I don't think this applies internally...

In general all usage related to webpack is fine. You should just not use it for other products or with bad intentions

**Comment by benhalverson** [comment]
Thanks @sokra 
I'll also ask in the openjs slack 👍
