### ISSUE TITLE
Permission to use logo in DevDocs

### ISSUE THREAD

**Issue by Thibaut** [webpack/media#7]
Hi

I started using the new webpack logo in DevDocs (http://devdocs.io - http://devdocs.io/webpack~2/). The project is open source (https://github.com/Thibaut/devdocs), but its license allows commercial use, and devdocs.io may from time to time run sponsorships, etc.

Please let me know if this is not an acceptable use of your logo.

**Comment by TheLarkInn** [comment]
@bebraw @JSFOwner is this legal to go via foundation guidelines? Just want to check before granting permission.

**Comment by bebraw** [comment]
Let's wait what @JSFOwner has to say since they manage the rights.

**Comment by bebraw** [comment]
@kborchers Any thoughts on this? Can they use webpack logo on DevDocs?

**Comment by kborchers** [comment]
👍 Yep this is a completely appropriate use of the trademark as it is just being used to describe the documentation to which they are linking.

Also, I apologize for the delay. I'm not sure why the JSFOwner ping never came through.

**Comment by Thibaut** [comment]
Great! Thanks everyone.
