### ISSUE TITLE
Permission to use logo in Firefox DevTools

### ISSUE THREAD

**Issue by clarkbw** [webpack/media#9]
👋 

We, Firefox Developer Tools, would like to use the webpack logo in the Firefox Debugger (aka debugger.html).  We are an open source project ([Firefox](https://firefox.com/)) and the [debugger source code](https://github.com/devtools-html/debugger.html) is available on GitHub.

We intend to use this icon: https://github.com/webpack/media/blob/master/logo/icon.svg

The icon placement will be in the [Source List](https://developer.mozilla.org/en-US/docs/Tools/Debugger/UI_Tour#Source_list_pane) view of the debugger and displayed only when the debugger has detected a webpack source mapping.

Here's the current view of a webpack source mapping.  We would replace the generic globe icon to the left of `webpack://` with the above webpack icon.

![](https://camo.githubusercontent.com/79899ebdb6db438bba2e49746fb78709286ad250/68747470733a2f2f7368697075736572636f6e74656e742e636f6d2f32366531363636323138316434653538623862636462313466613434373032382f53637265656e25323053686f74253230323031372d30342d3236253230617425323031302e30332e3436253230414d2e706e67)

We're tracking the issue here https://github.com/devtools-html/debugger.html/issues/2745 and expect to implement and land this change so we can have a working prototype.  We can hold off shipping of this particular feature to release until this issue is resolved.  

Thank you for your consideration. 🙇

**Comment by sokra** [comment]
Sure 👍

**Comment by clarkbw** [comment]
Thank you!

Would you prefer we raise all similar issues where the logo appears in the console or network panel?  Or would similar usage to this be considered acceptable as well?

**Comment by TheLarkInn** [comment]
No need to. Anywhere inside those panels would be fine! However, if something comes up outside of there let us know (just incase).

**Comment by clarkbw** [comment]
Will do! And feel free to raise any issues with us, happy to help.
